# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: jrs

# SQL Server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jrsdb
  namespace: jrs
spec:
  selector:
    matchLabels:
      app: jrsdb
  template:
    metadata:
      labels:
        app: jrsdb
    spec:
      containers:
      - name: jrsdb
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: Pa$$w0rd!
---
apiVersion: v1
kind: Service
metadata:
  name: jrsdb
  namespace: jrs
  labels:
    app: jrsdb
spec:
  selector:
    app: jrsdb
  ports:
  - name: tcp
    port: 1433
    targetPort: 1433
  type: NodePort
# Web App
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jrsweb
  namespace: jrs
spec:
  selector:
    matchLabels:
      app: jrsweb
  template:
    metadata:
      labels:
        app: jrsweb
    spec:
      containers:
      - name: jrsweb
        image: ercz/jrsweb:1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__Server
          value: jrsdb
        - name: ConnectionStrings__DB
          value: JRSDB
        - name: ConnectionStrings__Username
          value: sa
        - name: ConnectionStrings__Password
          value: Pa$$w0rd!
---
apiVersion: v1
kind: Service
metadata:
  name: jrsweb
  namespace: jrs
  labels:
    app: jrsweb
spec:
  selector:
    app: jrsweb
  ports:
  - name: tcp
    port: 5001
    targetPort: 80
  type: NodePort
# Web API
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jrsapi
  namespace: jrs
spec:
  selector:
    matchLabels:
      app: jrsapi
  template:
    metadata:
      labels:
        app: jrsapi
    spec:
      containers:
      - name: jrsapi
        image: ercz/jrsapi:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__Server
          value: jrsdb
        - name: ConnectionStrings__DB
          value: JRSDB
        - name: ConnectionStrings__Username
          value: sa
        - name: ConnectionStrings__Password
          value: Pa$$w0rd!
---
apiVersion: v1
kind: Service
metadata:
  name: jrsapi
  namespace: jrs
  labels:
    app: jrsapi
spec:
  selector:
    app: jrsapi
  ports:
  - name: tcp
    port: 6001
    targetPort: 80
  type: NodePort