# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: jrs

# SQL
  kind: Deployment
  metadata:
    name:: jrsdb
  spec:
    selector:
      matchLabels:
        labels:
          app: jrsdb
      
# 