// <auto-generated />
using System;
using JewelryRentalSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JewelryRentalSystem.Migrations
{
    [DbContext(typeof(JRSDBContext))]
    [Migration("20230425182119_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JewelryRentalSystem.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustClassId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CustClassId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "02174cf0–9412–4cfe-afbf-59f706d72cf6",
                            AccessFailedCount = 0,
                            Address = "Sample Address",
                            ConcurrencyStamp = "d2811590-b67a-4936-9251-271fe1b8ab84",
                            ContactNo = "09876543211",
                            CustClassId = 5,
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "admin",
                            LastName = "admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECldNdohqcFLWw5vPkE8pQmImaV60RUOw6gWtvyhDXsMoY08VdLP2m5Gg1VOHZId5Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0e5217cd-68d8-4964-9b3d-519ced9ee70d",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com",
                            isActive = true
                        },
                        new
                        {
                            Id = "45e23747-27a5-48e9-b7a6-755bfbb86004",
                            AccessFailedCount = 0,
                            Address = "Sample Address",
                            Birthdate = new DateTime(2003, 4, 26, 2, 21, 18, 861, DateTimeKind.Local).AddTicks(252),
                            ConcurrencyStamp = "c4bc6ba6-7699-4bc6-8bf8-d76d1acc2abb",
                            ContactNo = "09876543211",
                            CustClassId = 5,
                            Email = "admin2@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "admin",
                            LastName = "admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN2@GMAIL.COM",
                            NormalizedUserName = "ADMIN2@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENyyW5de3BT6tpiKszCEug6XqHLt/wJ4Qxe9UMI7serbpQkyPrwwsWVbxs9AJ4vpuQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "abc6c47b-8e67-4b64-9f17-907833fdb671",
                            TwoFactorEnabled = false,
                            UserName = "admin2@gmail.com",
                            isActive = true
                        });
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"), 1L, 1);

                    b.Property<int>("AppointmentTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("ConfirmAppointment")
                        .HasColumnType("bit");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateOfAppointment")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleTimeId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("AppointmentTypeId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ScheduleTimeId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.AppointmentType", b =>
                {
                    b.Property<int>("AppointmentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentTypeId"), 1L, 1);

                    b.Property<string>("APTName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentTypeId");

                    b.ToTable("AppointmentTypes");

                    b.HasData(
                        new
                        {
                            AppointmentTypeId = 1,
                            APTName = "Pick-Up"
                        });
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"), 1L, 1);

                    b.Property<bool>("ConfirmRent")
                        .HasColumnType("bit");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductQty")
                        .HasColumnType("int");

                    b.Property<int>("RentDuration")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Ring"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Necklace"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Bracelet"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Earrings"
                        });
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.CustomerClassification", b =>
                {
                    b.Property<int>("CustomerClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerClassId"), 1L, 1);

                    b.Property<string>("CustomerClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemLimit")
                        .HasColumnType("int");

                    b.Property<int>("RentLimit")
                        .HasColumnType("int");

                    b.HasKey("CustomerClassId");

                    b.ToTable("CustomerClassifications");

                    b.HasData(
                        new
                        {
                            CustomerClassId = 1,
                            CustomerClassName = "Classic",
                            ItemLimit = 5,
                            RentLimit = 1
                        },
                        new
                        {
                            CustomerClassId = 2,
                            CustomerClassName = "Silver",
                            ItemLimit = 10,
                            RentLimit = 5
                        },
                        new
                        {
                            CustomerClassId = 3,
                            CustomerClassName = "Gold",
                            ItemLimit = 20,
                            RentLimit = 10
                        },
                        new
                        {
                            CustomerClassId = 4,
                            CustomerClassName = "Platinum",
                            ItemLimit = 0,
                            RentLimit = 0
                        },
                        new
                        {
                            CustomerClassId = 5,
                            CustomerClassName = "Admin",
                            ItemLimit = 0,
                            RentLimit = 0
                        });
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"), 1L, 1);

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            LocationName = "Makati City"
                        },
                        new
                        {
                            LocationId = 2,
                            LocationName = "Quezon City"
                        },
                        new
                        {
                            LocationId = 3,
                            LocationName = "Valenzuela City"
                        },
                        new
                        {
                            LocationId = 4,
                            LocationName = "Antipolo City"
                        },
                        new
                        {
                            LocationId = 5,
                            LocationName = "Taguig City"
                        });
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CustClassId")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<int>("ProductStock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CustClassId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 4,
                            CustClassId = 2,
                            ProductDescription = "Add a pop of color and a touch of magical charm to your looks with this pair of Enchanted Disney Fine Jewelry Dangle Earrings. Featuring a 14k rose gold finish, these sterling silver earrings glitter with class and beauty. Glistening Rose De France complement the pure sparkle of 1/10 CTTW of diamonds. With these beautiful earrings, you won't need magic hair that glows when you sing in order to shine.",
                            ProductImage = "/products/productImgs/ed1119de-f9af-4fd3-b97f-f75e8af8b9ea_earrings3.webp",
                            ProductName = "Enchanted Disney Fine Jewelry",
                            ProductPrice = 1250.0,
                            ProductStock = 4
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            CustClassId = 2,
                            ProductDescription = "Dress up like your favorite Disney Princess Snow White by wearing this Enchanted Disney Fine Jewelry Sterling Silver and 10K Rose Gold Ring with Diamond Accent and Red Garnet. Evoking the gentle yet stern personality of Disney's first princess, this ring is all about female empowerment. It's the jewel for the independent lady who still loves fashion pretend play but does it in a chic, stylish, and very sophisticated way.",
                            ProductImage = "/products/productImgs/6a33a5ce-c010-419a-99f7-1d6e5ef8d343_06-28-2020_SD_RGO8042_0308_72dpi_600x@2x.webp",
                            ProductName = "Diamond and Red Garnet Snow White Ring",
                            ProductPrice = 2450.0,
                            ProductStock = 5
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 4,
                            CustClassId = 2,
                            ProductDescription = "Such a classic pair of earrings but now given a magical twist. These rose-shaped studs with diamond center are crafted from 14k rose gold over sterling silver. They are part of the Enchanted Disney Fine Jewelry Collection and are inspired by Belle. With a design influenced by Belle's character, you'll see these rose earrings to be gentle and delicate yet very much capable of standing and shining on their own.",
                            ProductImage = "/products/productImgs/0332f9d5-a488-4011-a5e3-407a7ab96a86_06-11-2020_SD_ERO4580_0265_72dpi_800x.webp",
                            ProductName = "Maleficent Rose Ring",
                            ProductPrice = 1290.0,
                            ProductStock = 6
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            CustClassId = 1,
                            ProductDescription = "The ring that gets a lot of compliments. Why would anyone not notice this beauty? Crafted from 14k rose gold over sterling silver, here is a ring inspired by Belle and exudes her fierce but kind and gentle but strong character. Featuring a bypass shank with sides lined in diamonds and a centerpiece of meeting roses, the interesting design of this ring is meant to start conversations and leave impressions.",
                            ProductImage = "/products/productImgs/ed1119de-f9af-4fd3-b97f-f75e8af8b9ea_earrings3.webp",
                            ProductName = "Belle Rose Fashion Ring",
                            ProductPrice = 610.0,
                            ProductStock = 7
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            CustClassId = 1,
                            ProductDescription = "Celebrate your life that's full of contrast with this heart-shaped pendant inspired by Belle. Part of the Enchanted Disney Fine Jewelry Collection, this sterling silver pendant has its one side simple and the other embellished with diamonds and a 14k rose gold flower accent. Consider this necklace a symbolic accessory that will remind you of the importance of contrasts in order to find balance.",
                            ProductImage = "/products/productImgs/9a7cf85c-5c57-4571-b1b3-b5a0b9a50ecc_08-16-2018_SD_PDO3592_0003_300dpiNoBezel_600x@2x.webp",
                            ProductName = "Rose Fashion Pendant Necklace",
                            ProductPrice = 735.0,
                            ProductStock = 3
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            CustClassId = 1,
                            ProductDescription = "Rapunzel Collection Style #PDO5187-SP-DS Enchanted Disney Fine Jewelry Sterling Silver with 1/20 CTTW Dancing Diamond Rapunzel Pendant Necklace\r\nA twinkling sun pendant artistically rendered in sterling silver. This piece of fine jewelry is inspired by Rapunzel and is a must-have piece for any Disney fashionista. With this pendant, you not only get to level up your accessorizing but also get to wear a jewelry that's pretty and symbolic. Let this enchanting necklace shaped like the Kingdom of Corona's crest be a beautiful reminder of facing your fears and shining your light.",
                            ProductImage = "/products/productImgs/ed1119de-f9af-4fd3-b97f-f75e8af8b9ea_earrings3.webp",
                            ProductName = "Dancing Diamond Rapunzel Pendant Necklace",
                            ProductPrice = 528.0,
                            ProductStock = 9
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            CustClassId = 3,
                            ProductDescription = "What a lovely ring this is! The blend of color and sparkle works seamlessly and beautifully without pretension and flaunting. This Enchanted Disney Fine Jewelry Elsa Snowflake Ring is fashioned in 14K Rose Gold over Sterling Silver and displays the radiance of 1/6 carat total weight of diamonds. A Swiss Blue Topaz and a Rose-de-France bring even more grace and sophistication to this sculpted piece of jewelry.",
                            ProductImage = "/products/productImgs/e0e7d2b0-dbc8-4744-9dd2-09b53c36c81f_ring2.webp",
                            ProductName = "Rose-De-France Elsa Snowflake Ring",
                            ProductPrice = 2999.0,
                            ProductStock = 7
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1,
                            CustClassId = 3,
                            ProductDescription = "Be the voyager princess that you truly are and show great pride for who you are by wearing this Enchanted Disney Fine Jewelry Moana Wave Ring. Fashioned in sterling silver with 1/4 CTTW blue and white diamond, this glittering wave ring will fit your sea-loving, headstrong, and fearless personality. Let it make you stand out from the crowd while keeping you empowered to believe in yourself and stand your ground to fight for what you value.",
                            ProductImage = "/products/productImgs/d40ac081-7252-4d38-ae13-43d460359eff_090176_RG11593_0650_client_03_600x@2x.webp",
                            ProductName = "Wave Ring",
                            ProductPrice = 3460.0,
                            ProductStock = 6
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 4,
                            CustClassId = 3,
                            ProductDescription = "Want a jewelry that tells a story? Get yourself this pair of blazing sun earrings inspired by Rapunzel's tale. These Enchanted Disney Fine Jewelry earrings features a 10 karat yellow gold sunburst stud with a round solitaire diamond at its center. This fashion accessory will not only enhance your sense of style, it can also be a symbolic reminder for you to take a step out of your comfort zone, chase your dreams, and never give up.",
                            ProductImage = "/products/productImgs/8ba7413d-c5bb-4d86-b85d-3a8da19d587e_ERO2761Y1WDSZA_600x@2x.webp",
                            ProductName = "Sun Blaze Earrings",
                            ProductPrice = 2910.0,
                            ProductStock = 3
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 1,
                            CustClassId = 2,
                            ProductDescription = "Acknowledge a loved one's fearless and determined spirit with a Diamond Star Ring present inspired by the feisty fairy, Tinker Bell. This piece of jewelry is crafted from sterling silver and features four sparkling stars. Two twinkles with white diamond beauty and the other two glistens in vivid green tourmaline charm. The whimsical crossover style mirrors the vivacious personality of Tinkerbell and completes the fab fairy charm of this fashion jewelry.",
                            ProductImage = "/products/productImgs/6a33a5ce-c010-419a-99f7-1d6e5ef8d343_06-28-2020_SD_RGO8042_0308_72dpi_600x@2x.webp",
                            ProductName = "Diamond and Green Tourmaline Tinker Bell Star Ring",
                            ProductPrice = 1535.0,
                            ProductStock = 8
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 4,
                            CustClassId = 2,
                            ProductDescription = "Do you see yourself as somebody who has Tinker Bell's feisty spirit? This pair of whimsical earrings from Enchanted Disney Fine Jewelry is for you. Crafted in sterling silver, shaped into Tinker Bell's iconic pose, and dotted with 1/10 CTTW of diamonds, this pair of earrings will be a lovely addition to your jewelry collection. Wear this whenever you feel like you need a little inspiration to be brave, adventurous, determined, and creative like Tinker Bell.",
                            ProductImage = "/products/productImgs/b15d56ed-3e68-4e6f-b0ae-da9e97953104_ERO2574_angle_03_300dpi_600x@2x.webp",
                            ProductName = "Fine Jewelry Sterling Silver Earrings",
                            ProductPrice = 1419.0,
                            ProductStock = 5
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 1,
                            CustClassId = 1,
                            ProductDescription = "You don't have to grow up under the sea to love this sparkling ring. Inspired by the Little Mermaid, this Enchanted Disney Fine Jewelry Sterling Silver and Rose Gold Plating 1/10CTTW Ariel Shell Tiara Ring fits grown-ups who have never lost their childlike wonder. Among your thingamabobs, this one is sure to stand out with its good looks, whimsical charm, and seashell splendor.",
                            ProductImage = "/products/productImgs/341b9a28-10b7-41af-b959-25a67d2b321b_06-19-2018_SD_RGO7701_0031_72dpi_600x@2x.webp",
                            ProductName = "Ariel Shell Tiara Ring",
                            ProductPrice = 350.0,
                            ProductStock = 4
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 2,
                            CustClassId = 1,
                            ProductDescription = "A necklace you'll wear year-round. This Enchanted Disney Fine Jewelry 14K Yellow Gold over Sterling Silver with 1/10CTTW Diamonds and Smokey Quartz Pocahontas Medallion Pendant has a versatile aesthetic that will match any look. Aside from adding sparkle to what you wear, this necklace is also ready to bring personality to your style. Channel Pocahontas' free-spirited nature and look and feel confident while marching to the beat of your own drum.",
                            ProductImage = "/products/productImgs/96b1ec1c-752e-4755-b77f-5146b4d786f0_PDO9307SWYC4SQDJ_600x@2x.webp",
                            ProductName = "Medallion Pendant Necklace",
                            ProductPrice = 290.0,
                            ProductStock = 7
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 1,
                            CustClassId = 4,
                            ProductDescription = "This Enchanted Disney Fine Jewelry Belle Wedding Band is just like how the tale of Beauty and the Beast is both magical and beautiful. Featuring a 14k white gold and rose gold band with a row of brilliant diamonds, this is the ring that will sparkle divinely on your finger. Seal your love with some fairytale charm and let this ring be the dazzling reminder of the promise of a happy ever after.",
                            ProductImage = "/products/productImgs/acf14f77-f157-4129-bb94-72c8d1c8263c_31IfSg2Kx1L_600x@2x.webp",
                            ProductName = "Belle Wedding Band",
                            ProductPrice = 3690.0,
                            ProductStock = 3
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 1,
                            CustClassId = 1,
                            ProductDescription = "A floral jewelry to treasure, this Enchanted Disney Fine Jewelry Belle Rose Stud Earrings has a timeless appeal that your beloved will surely appreciate. Crafted in 14k rose gold over sterling, each rose-shaped stud comes with a diamond center. These studs blooming with elegance make for a refreshing statement piece. The size is perfect for daily wear, for day or night outfits. You'd be impressed by how these romantic rose earrings give a chic touch to your looks.",
                            ProductImage = "/products/productImgs/5ca8ef63-53b6-416c-9d13-75f22dd2592c_earrings2.webp",
                            ProductName = "Maleficent Rose Pendant Necklace",
                            ProductPrice = 400.0,
                            ProductStock = 5
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 4,
                            CustClassId = 1,
                            ProductDescription = "Pretty with a touch of whimsy. If you're looking for a gift for a lady who has it all, this pair of Majestic Princess Crown Earrings would be a wonderful choice. It is from the Enchanted Disney Fine Jewelry and is crafted in Sterling Silver decorated with 1/10 carat total weight of diamonds. These earrings can instantly upstyle any outfit and give it a playful yet still sophisticated vibe.",
                            ProductImage = "/products/productImgs/f97e401a-d915-47e3-90e2-84086332d972_ERO2557-SI3-DSJC_800x.webp",
                            ProductName = "Diamond Majestic Princess Crown Earrings",
                            ProductPrice = 411.0,
                            ProductStock = 5
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 1,
                            CustClassId = 2,
                            ProductDescription = "Bringing color and sparkle to your fairytale is this Enchanted Disney Fine Jewelry Cinderella Ring. Intricately crafted from sterling silver, its polished shank is dotted with 1/5 CTTW diamonds and neatly topped with a chic London Blue Topaz center stone. This sophisticated band effortlessly exudes beauty, romance and elegance making it the perfect ring for the love of your life who personifies grace and poise.",
                            ProductImage = "/products/productImgs/8b35a5bd-9edb-46c5-8dbc-3ff0c4e4bffa_07-18-2018_SD_RGO8220_0046_300dpi_800x.webp",
                            ProductName = "Diamond and London Blue Topaz Ring",
                            ProductPrice = 1800.0,
                            ProductStock = 8
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 1,
                            CustClassId = 2,
                            ProductDescription = "Like Elsa, this pair of Enchanted Disney Fine Jewelry Diamonds and Swiss Blue Topaz Dangling Earrings make a statement. They accurately display the character of the Queen of Arendelle - elegant, dramatic, and confident. Exude the same personality by adding these earrings to your wardrobe. Expect this fine piece of jewelry bring an effortless shine and shimmer to whatever you wear.",
                            ProductImage = "/products/productImgs/b0066390-209e-4729-8c88-5bf409c7bf5a_06-11-2020_SD_ERO4580_0265_72dpi_800x.webp",
                            ProductName = "Swiss Blue Topaz Dangling Earrings",
                            ProductPrice = 2290.0,
                            ProductStock = 5
                        });
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.ScheduleTime", b =>
                {
                    b.Property<int>("TimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeId"), 1L, 1);

                    b.Property<string>("SchedTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TimeId");

                    b.ToTable("ScheduleTimes");

                    b.HasData(
                        new
                        {
                            TimeId = 1,
                            SchedTime = "8:00:00 - 9:00:00"
                        },
                        new
                        {
                            TimeId = 2,
                            SchedTime = "9:00:00 - 10:00:00"
                        },
                        new
                        {
                            TimeId = 3,
                            SchedTime = "10:00:00 - 11:00:00"
                        },
                        new
                        {
                            TimeId = 4,
                            SchedTime = "11:00:00 - 12:00:00"
                        },
                        new
                        {
                            TimeId = 5,
                            SchedTime = "13:00:00 - 14:00:00"
                        },
                        new
                        {
                            TimeId = 6,
                            SchedTime = "14:00:00 - 15:00:00"
                        },
                        new
                        {
                            TimeId = 7,
                            SchedTime = "15:00:00 - 16:00:00"
                        },
                        new
                        {
                            TimeId = 8,
                            SchedTime = "16:00:00 - 17:00:00"
                        });
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"), 1L, 1);

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("JewelryRentalSystem.ViewModels.ActivateAccountViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ActivateAccountViewModel");
                });

            modelBuilder.Entity("JewelryRentalSystem.ViewModels.ModifyAccountViewModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthdate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ModifyAccountViewModel");
                });

            modelBuilder.Entity("JewelryRentalSystem.ViewModels.ProfileViewModel", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthdate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemLimit")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RentLimit")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("ProfileViewModel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9ea94376-bae3-4592-b2ef-16e2222ec6f4",
                            ConcurrencyStamp = "9ea94376-bae3-4592-b2ef-16e2222ec6f4",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "f913644d-d5a1-4c4a-a73b-dacc6a8c7898",
                            ConcurrencyStamp = "f913644d-d5a1-4c4a-a73b-dacc6a8c7898",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "02174cf0–9412–4cfe-afbf-59f706d72cf6",
                            RoleId = "9ea94376-bae3-4592-b2ef-16e2222ec6f4"
                        },
                        new
                        {
                            UserId = "45e23747-27a5-48e9-b7a6-755bfbb86004",
                            RoleId = "9ea94376-bae3-4592-b2ef-16e2222ec6f4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.ApplicationUser", b =>
                {
                    b.HasOne("JewelryRentalSystem.Models.CustomerClassification", "CustomerClassification")
                        .WithMany("Users")
                        .HasForeignKey("CustClassId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CustomerClassification");
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.Appointment", b =>
                {
                    b.HasOne("JewelryRentalSystem.Models.AppointmentType", "AppointmentType")
                        .WithMany()
                        .HasForeignKey("AppointmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewelryRentalSystem.Models.ApplicationUser", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JewelryRentalSystem.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewelryRentalSystem.Models.ScheduleTime", "ScheduleTime")
                        .WithMany()
                        .HasForeignKey("ScheduleTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppointmentType");

                    b.Navigation("Customer");

                    b.Navigation("Location");

                    b.Navigation("ScheduleTime");
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.Cart", b =>
                {
                    b.HasOne("JewelryRentalSystem.Models.ApplicationUser", "Customer")
                        .WithMany("Carts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewelryRentalSystem.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewelryRentalSystem.Models.Transaction", "Transaction")
                        .WithMany("Carts")
                        .HasForeignKey("TransactionId");

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.Product", b =>
                {
                    b.HasOne("JewelryRentalSystem.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewelryRentalSystem.Models.CustomerClassification", "CustomerClassification")
                        .WithMany("Products")
                        .HasForeignKey("CustClassId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("CustomerClassification");
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.Transaction", b =>
                {
                    b.HasOne("JewelryRentalSystem.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("JewelryRentalSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("JewelryRentalSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewelryRentalSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("JewelryRentalSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.ApplicationUser", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Carts");
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.CustomerClassification", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("JewelryRentalSystem.Models.Transaction", b =>
                {
                    b.Navigation("Carts");
                });
#pragma warning restore 612, 618
        }
    }
}
